name: Lint

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Ruff & Black
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Python einrichten
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install black ruff

      - name: Ruff Lint
        run: ruff check .

      - name: Black Formatierung prüfen
        run: black --check .
